---
- hosts: all
  gather_facts: no

  tasks:
    - name: Check for SSH prompt (timeout 10min)
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        timeout: 600
      delegate_to: localhost
