- hosts: spoke_routers
  gather_facts: no
  tasks:
    - set_fact:
        hub_router: "{{ groups.hub_routers[0] }}"

    - include_role:
        name: network-dmvpn
      vars:
        dmvpn_node_type: spoke
        dmvpn_tunnel_ip: "{{ dmvpn_tunnel_network | ipaddr(dmvpn_site_number|int + 1) }}"
        dmvpn_loopback_ip: "{{ dmvpn_loopback_network | ipaddr(dmvpn_site_number|int + 1) | ipaddr('address')}}/32"
        dmvpn_hub_tunnel_ip: "{{ dmvpn_tunnel_network | ipaddr(1) }}"
        dmvpn_hub_ip: "{{ hostvars[hub_router].ansible_host }}"
        dmvpn_tunnel_interface: "{{ interfaces.0.name }}"
        dmvpn_site_networks:
          - "{{ interfaces.1.ip | ipaddr('network') }}/{{ interfaces.1.ip | ipaddr('prefix') }}"

- hosts: hub_routers
  gather_facts: no
  tasks:
    - include_role:
        name: network-dmvpn
      vars:
        dmvpn_node_type: hub
        dmvpn_tunnel_ip: "{{ dmvpn_tunnel_network | ipaddr(dmvpn_site_number|int + 1) }}"
        dmvpn_loopback_ip: "{{ dmvpn_loopback_network | ipaddr(dmvpn_site_number|int + 1) | ipaddr('address')}}/32"
        dmvpn_hub_tunnel_ip: "{{ dmvpn_tunnel_network | ipaddr(1) }}"
        dmvpn_tunnel_interface: "{{ interfaces.0.name }}"
        dmvpn_site_networks:
          - "{{ interfaces.1.ip | ipaddr('network') }}/{{ interfaces.1.ip | ipaddr('prefix') }}"
