---
- name: Make sure that we can ping the hosts from the routers
  hosts: routers
  gather_facts: no
  tasks:
    - set_fact:
        dmvpn_tunnel_ip: "{{ dmvpn_tunnel_network | ipaddr(dmvpn_site_number|int + 1) | ipaddr('address') }}"
        dmvpn_loopback_ip: "{{ dmvpn_loopback_network | ipaddr(dmvpn_site_number|int + 1) | ipaddr('address')}}"

    - name: Ping tunnel interfaces
      net_ping:
        dest: "{{ hostvars[item].dmvpn_tunnel_ip }}"
        source: Tunnel{{ dmvpn_tunnel_number | default (0)}}
      when: item != inventory_hostname
      with_items: "{{ groups.routers | default([]) }}"

    - name: Ping loopback interfaces
      net_ping:
        dest: "{{ hostvars[item].dmvpn_loopback_ip }}"
        source: Loopback{{ dmvpn_loopback_number | default (0) }}
      when: item != inventory_hostname
      with_items: "{{ groups.routers | default([]) }}"
