---
- hosts: network
  gather_facts: no
  tasks:
    - name: Check for SSH prompt (timeout 10min)
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        timeout: 600
      delegate_to: localhost

    - name: Configure the hostname and domain name
      net_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ global_domain_name }}"
        domain_search: "{{ global_domain_search | default(omit) }}"
        name_servers: "{{ global_nameservers | default(omit) }}"

    - name: Enable the interfaces
      net_interface:
        name: "{{ item.name }}"
        enabled: True
      when: item.ip | ipaddr
      with_items: "{{ interfaces }}"

    - name: Set interface IP
      net_l3_interface:
        name: "{{ item.name }}"
        ipv4: "{{ item.ip }}"
      when: item.ip | ipaddr
      with_items: "{{ interfaces }}"
