---
- hosts: network
  gather_facts: no
  vars:
    site_domain_name: 'example.net'
    network_name_servers:
      - 8.8.8.8
      - 8.8.4.4
    network_domain_search:
      - example.net

  tasks:
    - name: Check for SSH prompt (timeout 10min)
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        timeout: 600
      delegate_to: localhost

    - name: Configure the hostname and domain name
      net_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ site_domain_name }}"
        domain_search: "{{ network_domain_search | default(omit) }}"
        name_servers: "{{ network_name_servers | default(omit) }}"

    - name: Enable the interfaces
      net_interface:
        name: "{{ item.name }}"
        enabled: True
      when: item.ip | ipaddr
      with_items: "{{ interfaces }}"

    - name: Set interface IP
      net_l3_interface:
        name: "{{ item.name }}"
        ipv4: "{{ item.ip }}"
      when: item.ip | ipaddr
      with_items: "{{ interfaces }}"
