- include_tasks: get-token.yml
  when: tower_api_token is not defined

- name: Add credential {{ tower_api_in_name }}
  uri:
    url: "https://{{ tower_api_endpoint }}/api/v2/credentials/"
    method: POST
    headers:
      Authorization: "Token {{ tower_api_token }}"
    body:
      name: "{{ tower_api_in_name }}"
      description: "{{ tower_api_in_description | default('') }}"
      organization: "{{ tower_api_in_organization | default('') }}"
      user: "{{ tower_api_in_username | default('') }}"
      team: "{{ tower_api_in_team | default('') }}"
      credential_type: "{{ tower_api_in_credential_type }}"
      inputs:
        password: "{{ tower_api_in_password | default('') }}"
        ssh_key_data: "{{ tower_api_in_ssh_key_data }}"
    body_format: json
    validate_certs: "{{ validate_certs }}"
    return_content: yes
    status_code: 201
  register: post_result
  failed_when: "'exists' not in post_result.content"
