- name: Get all hosts
  uri:
    url: "https://{{ tower_api_endpoint }}/api/v2/hosts/"
    method: GET
    headers:
      Authorization: "Token {{ tower_api_token }}"
    body_format: json
    validate_certs: "{{ validate_certs }}"
    return_content: yes
  ignore_errors: no
  register: get_result

- debug: var=get_result

- set_fact:
    tower_api_host_map: "{{ tower_api_host_map|default({}) | combine( { result_item.name: result_item.id } ) }}"
  with_items: "{{ get_result.json.results }}"
  loop_control:
    loop_var: result_item
