- set_fact:
    tower_api_group_map: {}
  when: tower_api_group_map is not defined

- name: Get all groups
  uri:
    url: "https://{{ tower_api_endpoint }}/api/v2/groups/"
    method: GET
    headers:
      Authorization: "Token {{ tower_api_token }}"
    body_format: json
    validate_certs: "{{ validate_certs }}"
    return_content: yes
  ignore_errors: no
  register: get_result

- set_fact:
    tower_api_group_map: "{{ tower_api_group_map | combine( { result_item.name: result_item.id } ) }}"
  with_items: "{{ get_result.json.results }}"
  loop_control:
    loop_var: result_item
