- name: Get API Token
  uri:
    url: "https://{{ tower_api_endpoint }}/api/v2/authtoken/"
    method: POST
    body:
      username: "{{ tower_api_username }}"
      password: "{{ tower_api_password }}"
    body_format: json
    validate_certs: "{{ validate_certs }}"
    return_content: yes
  no_log: false  # Don't show output as your password will be on the URI string
  register: api_token_output

- set_fact:
    tower_api_token: "{{ api_token_output.json.token }}"
